# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27a87f9520b9156d94cae6dc40f23f94bd248b43418813d64324024271dde1c72b6b18cfc365aec3ce61b9f18852719d5d3d2bcac4faaa6f6635a95fe965adb3

test:
  secret_key_base: a5d8406d1d82c48325ecadf42bdaa6df23f16a644a610ea3a14bb76ccd140d51041bb60287b054ab4859989f07ea3df3b5301b07308da8205c7414846999c7b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
